Task part 3
iL53n/test-guru pull request #2
Opened 2019-03-15 20:00 UTC by iL53n

2019-03-15 20:09 UTC, BubuntuClu requested changes

2019-03-15 20:09 UTC, BubuntuClu commented on db/migrate/20190315191326_create_tests.rb
> +      t.integer :level
а где связь с категорией? вспоминай про внешние ключи. и советую сначала сделать таблицу категорий, а потом уже таблицу тестов

2019-03-15 20:09 UTC, BubuntuClu commented on db/migrate/20190315191510_create_questions.rb
> +      t.string :body
где связь с таблицей тестов?

2019-03-15 20:09 UTC, BubuntuClu commented on db/migrate/20190315191628_create_answers.rb
> +      t.boolean :correct
где связь с вопросапми?

2019-03-15 20:09 UTC, BubuntuClu commented on db/migrate/20190315192916_add_tests_title_not_null.rb
> +class AddTestsTitleNotNull < ActiveRecord::Migration[5.2]
однотипные миграции можно в одну объединить, тогда у тебя будет всего две, одна задает null ограничения, вторая дефолтные значения

2019-03-15 21:18 UTC, iL53n commented on db/migrate/20190315191326_create_tests.rb
> +      t.integer :level
добавил

2019-03-15 21:18 UTC, iL53n commented on db/migrate/20190315191510_create_questions.rb
> +      t.string :body
добавил

2019-03-15 21:18 UTC, iL53n commented on db/migrate/20190315191628_create_answers.rb
> +      t.boolean :correct
добавил

2019-03-15 21:19 UTC, iL53n commented on db/migrate/20190315192916_add_tests_title_not_null.rb
> +class AddTestsTitleNotNull < ActiveRecord::Migration[5.2]
добавил

2019-03-16 08:07 UTC, iL53n commented on db/migrate/20190315211702_add_default.rb
> +class AddDefault < ActiveRecord::Migration[5.2]
# change_column_default :tests, :level, from: 0, to: false

2019-03-17 17:22 UTC, merged