Task part 6
iL53n/test-guru pull request #5
Opened 2019-03-20 20:11 UTC by iL53n

2019-03-21 06:23 UTC, BubuntuClu requested changes

2019-03-21 06:23 UTC, BubuntuClu commented on app/models/question.rb
> +  validate :validate_amt_answers
что такое `amt`?

2019-03-21 06:23 UTC, BubuntuClu commented on app/models/question.rb
> +  def validate_amt_answers
эта валидация не будет работать, так как просят в задании. это валидации будет отрабатывать при создании вопроса. а при создании вопроса у него нет ответов. после создания вопроса, мы сможем создать сколько угодно ответов.

эта валидация должна быть в моделе ответов

2019-03-21 06:23 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :tests_by_category, -> (category) { Test.joins(:category).where(categories: { title: category }) }
`joins(:category).where(categories: { title: category })`

2019-03-21 06:23 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :titles_by_category, -> (category) { tests_by_category(category).order(title: :desc).pluck(:title) } # <--
сортировку и выборку не надо помещать в скоуп. так как скоуп универсальный метод, который может использоваться в разных частях приложения, и там тебе может потребоваться другая сортировка или другая выборка полей. метод надо оставить и основную часть просто заменить на использование скоупа

2019-03-21 17:45 UTC, iL53n commented on app/models/question.rb
> +  validate :validate_amt_answers
amount :)

2019-03-21 17:47 UTC, iL53n commented on app/models/test.rb
> +  scope :tests_by_category, -> (category) { Test.joins(:category).where(categories: { title: category }) }
поправил

2019-03-21 18:19 UTC, iL53n commented on app/models/test.rb
> +  scope :titles_by_category, -> (category) { tests_by_category(category).order(title: :desc).pluck(:title) } # <--
`where` остави в скоупе, `order`, `pluck` закинул в метод

2019-03-21 18:36 UTC, iL53n commented on app/models/question.rb
> +  def validate_amt_answers
изменил

2019-03-21 19:12 UTC, iL53n commented
![](https://github.trello.services/images/mini-trello-icon.png) [Задание к уроку "Валидации и scope-методы"](https://trello.com/c/BZNgthpE/44-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA-%D1%83%D1%80%D0%BE%D0%BA%D1%83-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8-%D0%B8-scope-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B)

2019-03-21 21:48 UTC, BubuntuClu commented on app/models/answer.rb
> +  def question_answers #если возвращает nil, то 'NoMethodError (undefined method `answers' for nil:NilClass)'
а почему у тебя `nil` возвращает? у тебя ответ всегда должен быть привязан к вопросу. да и сам метод смысла не несет. зачем тебе синоним такой?

2019-03-22 05:11 UTC, iL53n commented on app/models/answer.rb
> +  def question_answers #если возвращает nil, то 'NoMethodError (undefined method `answers' for nil:NilClass)'
1. если мы на несохраненный объект вызываем `valid?`
2. я рассматривал `question_answers` как метод-адаптер. `question.answers.count` не нарушает закон Деметры ?

2019-03-22 16:56 UTC, iL53n commented
![](https://github.trello.services/images/mini-trello-icon.png) [merge](https://trello.com/c/BmZurmKD/56-merge)

2019-03-22 20:28 UTC, BubuntuClu commented on app/models/answer.rb
> +  def question_answers #если возвращает nil, то 'NoMethodError (undefined method `answers' for nil:NilClass)'
1. в любом случае ты через ассоциации создаешь ответ, там будет привязка к вопросу, даже если ответ еще не сохранен.
2. ну если рассматривать это `a.b.Method() нарушает Закон Деметры, а код a.Method() является корректным.` , то нарушает. но в данном случае я не вижу в чем разница между тем что ты напрямую вызовешь `question.answers.count` или сделаешь метод, который сделает тоже самое.

2019-03-23 06:32 UTC, iL53n commented on app/models/answer.rb
> +  def question_answers #если возвращает nil, то 'NoMethodError (undefined method `answers' for nil:NilClass)'
1. ок
2. согласен, в данном случаи разницы нет

2019-03-23 06:34 UTC, merged